# Generated by Django 5.1.6 on 2025-02-22 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_remove_post_comment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="following",
            old_name="followed",
            new_name="followers",
        ),
        migrations.RenameField(
            model_name="following",
            old_name="follower",
            new_name="following",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
