# Generated by Django 5.1.6 on 2025-02-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
