# Generated by Django 5.1.6 on 2025-02-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_post_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("computer_graphics", "Computer Graphics"),
                    ("graphic_designs", "Graphic Designs"),
                    ("3d_models", "3D Models"),
                    ("painting", "Painting"),
                    ("photography", "Photography"),
                    ("music", "Music"),
                ],
                default="computer_graphics",
                max_length=20,
            ),
        ),
    ]
