# Generated by Django 5.1.6 on 2025-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("computer_graphics", "3D Computer Graphics"),
                    ("graphic_designs", "Graphic Designs"),
                    ("threeD_models", "3D Models"),
                    ("painting", "Painting"),
                    ("photography", "Photography"),
                    ("music", "Music"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
