# Generated by Django 5.1.6 on 2025-02-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_deletedlisting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeletedListing",
        ),
    ]
